"""
agents/reporter.py
───────────────────
The Reporter Agent compiles the final Threat Fact Sheet from all prior state.

Phase 1 behaviour (stub):
  - Builds a structured markdown Threat Fact Sheet from state data
  - Marks job as COMPLETE
  - Writes fact_sheet to state

Phase 3 will add:
  - Discord/Slack webhook posting
  - noveum_trace span wrapping
  - Groq/Llama 3 for narrative summary generation
"""

from __future__ import annotations
import datetime
from backend.core.state import (
    SentinelState, JobStatus, AgentMessage, ThreatFactSheet
)
from backend.core.tracing import trace_span


def _determine_severity(anomaly_score: float, confidence: float) -> str:
    combined = (anomaly_score + confidence) / 2
    if combined >= 0.85:
        return "CRITICAL"
    elif combined >= 0.70:
        return "HIGH"
    elif combined >= 0.50:
        return "MEDIUM"
    return "LOW"


def reporter_node(state: SentinelState) -> SentinelState:
    with trace_span(state, "reporter", "compile_fact_sheet") as span:
        evidence = state.get("evidence", {})
        context  = state.get("context", {})
        problem  = state.get("problem_statement", "N/A")

        anomaly_score = evidence.get("anomaly_score", 0.0)
        confidence    = context.get("confidence", 0.0)
        severity      = _determine_severity(anomaly_score, confidence)

        # Build markdown Threat Fact Sheet
        ips      = ", ".join(evidence.get("matched_ips", [])) or "None detected"
        hashes   = ", ".join(evidence.get("matched_hashes", [])) or "None detected"
        intel    = context.get("threat_intel", [])
        snippets = context.get("search_snippets", [])

        intel_md = "\n".join(
            f"  - **{i.get('ip', '?')}**: {i.get('notes', '')}" for i in intel
        ) or "  - No threat intel matches."

        snippets_md = "\n".join(f"  - {s}" for s in snippets) or "  - No search data."

        markdown = f"""# 🛡️ Sentinel-Ops — Threat Fact Sheet
**Generated:** {datetime.datetime.utcnow().isoformat()}Z
**Severity:** {severity}
**Confidence:** {confidence:.0%}

---

## Alert Summary
> {problem}

## Evidence
- **Anomaly Score:** {anomaly_score:.2f}
- **Reason:** {evidence.get("anomaly_reason", "N/A")}
- **Suspicious IPs:** {ips}
- **File Hashes:** {hashes}

## Raw Log Sample
```
{"  ".join(evidence.get("raw_logs", ["No logs captured"])[:3])}
```

## Threat Intelligence
{intel_md}

## Search Context
{snippets_md}

## Recommendations
1. Block IP `{ips}` at perimeter firewall immediately.
2. Reset credentials for the targeted account.
3. Review SSH config: enforce key-based auth, disable password login.
4. Check for lateral movement from source IP across the subnet.

## MITRE ATT&CK (Inferred)
- T1110 — Brute Force
- T1078 — Valid Accounts (post-compromise risk)

---
*Generated by Sentinel-Ops v0.1 · [STUB mode — Phase 1]*
"""

        fact_sheet: ThreatFactSheet = {
            "summary":         f"SSH brute-force detected from {ips}. Severity: {severity}.",
            "severity":        severity,
            "recommendations": [
                "Block attacker IP at firewall.",
                "Reset targeted account credentials.",
                "Enable key-based SSH auth.",
            ],
            "mitre_tactics": ["T1110", "T1078"],
            "raw_markdown":  markdown,
        }

        msg: AgentMessage = {
            "role": "reporter",
            "content": f"Threat Fact Sheet compiled. Severity: {severity}.",
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }

        state["fact_sheet"]  = fact_sheet
        state["job_status"]  = JobStatus.COMPLETE
        state.setdefault("messages", []).append(msg)

        span["result"] = f"severity={severity} fact_sheet_chars={len(markdown)}"

    return state
